# Site settings
title: Nerdipity - Michelantonio Trizio
description: 'Engineer, Entrepreneur, Android dev'
motto: '#nerdipity is the way'
url: 'http://joshgerdes.com/jekyll-uno'
baseurl: '/jekyll-uno/'
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Michelantonio Trizio'
  email: mikelantonio.trizio@gmail.com
  twitter_username: mik3lantoni0
  github_username:  Mikelantonio
  linkedin_username:  michelantoniotrizio
  stackoverflow_username: 1049741/michelantonio-trizio
  medium_username: mikelantonio.trizio

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
